version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"

  app:
    image: python:3.10
    volumes:
      - ./app:/app
      - ./app:/var/log
    working_dir: /app
    command: python sample_app.py
